apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-tester
  namespace: jmeter
spec:
  ttlSecondsAfterFinished: 120 #Change back the value to 60 after testing
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: jmeter-tester
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 120 #change to 60 after testing
      containers:
        - name: jmeter-tester
          image: domuharahap/jmeter-tester:sprint.1.0
          imagePullPolicy: Always
          env:
            - name: JVM_THREADS
              value: "50"
            - name: JVM_LOOPS
              value: "-1"
            - name: JVM_DURATION
              value: "600"
            # Overridden at runtime by runJmeterTest() to point at the dtpay ingress URL
            - name: JVM_APP_URL
              value: "didactic-capybara-95q7jrr6j7pcxv77-80.app.github.dev"
            - name: JVM_DT_URL
              valueFrom:
                secretKeyRef:
                  name: dynatrace-creds
                  key: DT_ENVIRONMENT
            - name: JVM_DT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace-creds
                  key: DT_OPERATOR_TOKEN
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
